version: "3"
services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run dev:watch
    volumes:
      - .:/usr/src/app/src
      - nodemodules:/usr/src/app/node_modules
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:newPassword@postgres:5432/recognize
      NODE_ENV: development
      PORT: 3000
    ports:
      - "3000:3000"
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    networks:
      - postgres
    volumes:
      - postgres:/data/postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: newPassword
      POSTGRES_DB: recognize
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    logging:
      driver: none 
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8080:80"
    networks:
      - postgres
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres
networks:
  postgres:
    driver: bridge
volumes:
    postgres:
    pgadmin:
    nodemodules: